### ISSUE TITLE
Evaluate a way to use CLI deployment rather than deployment in Python for Azure Function

### ISSUE THREAD

**Issue by sbaidachni** [microsoft/mlops-aisearch-pull#57]
https://github.com/microsoft/mlops-promptflow-prompt/blob/development/.github/workflows/basic_flow_ci.yml#L102 as a reference

**Comment by radiant-tangent** [comment]
Pros of using existing python implementation:
- It's already written and tested
- Uses existing configuration (doesn't require additional workflow variables)
- Allows for polling to determine whether or not the functions are ready to test
- Is testable outside of github workflow and works across AzDO, github, and gitlab

Pros of switching to CLI deployment within github workflow:
- Less code, less code maintenance
- Used in other projects
- Polling could be implemented as separate workflow step, before we run the functions

Weighing the positives of each approach, it is decided that we will stick with the python implementation at this time. For future projects, if only using github/azDO, it is probably a good idea to implement the CLI deployment instead of the python deployment as there will be less code to maintain overall.
