### ISSUE TITLE
Define and implement a cleanup strategy

### ISSUE THREAD

**Issue by sbaidachni** [microsoft/mlops-aisearch-pull#8]
Python script.
```[tasklist]
### Tasks
- [x] Clean up index, indexer, and skillset
```

**Comment by radiant-tangent** [comment]
Reopening because workflow is not working.  The source branch name is not retrieved corrrectly.  Here's an example run that shows cleanup not working: https://github.com/microsoft/mlops-aisearch-pull/actions/runs/9420474596/job/25952632428

**Comment by radiant-tangent** [comment]
This was failing because I deleted the source branch before the github action had a chance to get to the cleanup process.  Going forward, I'll add documentation to the repo to not delete branches immediately after merge and instead wait for the cleanup process to conclude before deleting the merged branch.

In the future, we could modify the workflow to use AzDO and Github specific commands to get the source branch.
